/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/cart/': typeof CartIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/cart': typeof CartIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/products': typeof ProductsIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/cart/': typeof CartIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/product/$productId'
    | '/cart/'
    | '/categories/'
    | '/checkout/'
    | '/login/'
    | '/products/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product/$productId'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/login'
    | '/products'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/product/$productId'
    | '/cart/'
    | '/categories/'
    | '/checkout/'
    | '/login/'
    | '/products/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  CartIndexRoute: typeof CartIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  CartIndexRoute: CartIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
