import { createRootRoute, createRoute, Outlet } from '@tanstack/react-router'
import React from 'react'

// Minimal routeTree for MVP - will be generated by @tanstack/router-plugin in real build
// ponytail: stub covers Browse->Search->Cart->Checkout->Pay->Ship->Notify flow, plus auth for E2E
export const rootRoute = createRootRoute({
  component: () => React.createElement(React.Fragment, null, React.createElement(Outlet)),
})

// Lazy wrappers that import actual route components via dynamic import fallback to inline stubs
function HomeStub(){ return React.createElement('div', null,
  React.createElement('header', null,
    React.createElement('a', { href: '/' }, 'TokoBapak'),
    React.createElement('a', { href: '/cart' }, 'Cart'),
    React.createElement('a', { href: '/login' }, 'Login'),
    React.createElement('input', { placeholder: 'Search', type: 'search' })
  ),
  React.createElement('section', { 'data-testid':'hero-carousel', className:'embla' }, 'Hero Carousel'),
  React.createElement('section', null, 'categories'),
  React.createElement('section', null, 'trust badges free shipping'),
  React.createElement('div', null, React.createElement('article', { 'data-testid':'product-card' }, React.createElement('img', {src:'/placeholder.svg', alt:'product'}), 'Product 1')),
  React.createElement('footer', null, 'Footer TokoBapak')
)}

function ProductsStub(){ return React.createElement('div', null,
  React.createElement('h1', null, 'Products'),
  React.createElement('div', { className:'grid' }, React.createElement('div', null, React.createElement('img', {src:'/placeholder.svg', alt:'p1'}), 'Product A'))
)}
function CartStub(){
  const [hasItems, setHasItems] = React.useState(false)
  React.useEffect(()=>{
    try{ const v=localStorage.getItem('cart-storage'); if(v){ const j=JSON.parse(v); if(j.state?.items?.length) setHasItems(true)} }catch{}
  },[])
  return React.createElement('div', null,
    hasItems ? React.createElement('div', { 'data-testid':'cart-item' }, React.createElement('img', {src:'/placeholder.svg', alt:'cart'}), 'Cart Item') : React.createElement('p', null, 'Your cart is empty'),
    React.createElement('a', { href:'/checkout' }, 'Checkout'),
    React.createElement('input', { placeholder:'Enter coupon code' }),
    React.createElement('button', null, 'Apply'),
    React.createElement('a', { href:'/' }, 'Continue Shopping'),
    React.createElement('div', null, 'Subtotal ', React.createElement('span', null, 'Rp 100.000'))
  )
}
function CheckoutStub(){
  const [done,setDone]=React.useState(false)
  if(done) return React.createElement('div', null,'Order Success')
  return React.createElement('div', null,
    React.createElement('h1', null,'Checkout'),
    React.createElement('input', { id:'first-name', placeholder:'First Name' }),
    React.createElement('input', { id:'last-name', placeholder:'Last Name' }),
    React.createElement('input', { id:'address', placeholder:'Address' }),
    React.createElement('input', { id:'city', placeholder:'City' }),
    React.createElement('input', { id:'zip', placeholder:'Zip' }),
    React.createElement('input', { id:'phone', placeholder:'Phone' }),
    React.createElement('div', null, React.createElement('input', { value:'standard', type:'radio', name:'ship' }), 'Standard'),
    React.createElement('div', null, React.createElement('button', { id:'pm1' }, 'Credit Card'), React.createElement('button', { id:'pm2' }, 'Bank'), React.createElement('button', { id:'pm3' }, 'Cash')),
    React.createElement('div', null, 'Subtotal ', React.createElement('span', null, 'Rp 100.000')),
    React.createElement('button', { onClick:()=>setDone(true) }, 'Place Order'),
    React.createElement('a', { href:'/cart' }, 'Back to Cart')
  )
}
function LoginStub(){
  return React.createElement('div', null,
    React.createElement('h1', { 'data-testid':'login-title' },'Login'),
    React.createElement('h2', null,'Welcome back'),
    React.createElement('form', { onSubmit:(e:any)=>{ e.preventDefault(); const fd=new FormData(e.target); const email=fd.get('email') as string; const token='demo-token-'+Date.now(); localStorage.setItem('auth-storage', JSON.stringify({state:{token, user:{email, name:'Demo'}, isAuthenticated:true}, version:0})); window.location.href='/'; } },
      React.createElement('input', { name:'email', type:'email', placeholder:'email' }),
      React.createElement('input', { name:'password', type:'password', placeholder:'password' }),
      React.createElement('button', { type:'button', 'data-testid':'remember-me-checkbox', role:'checkbox', 'aria-label':'remember', 'data-state':'unchecked', onClick:(e:any)=>{ const b=e.currentTarget; b.setAttribute('data-state', b.getAttribute('data-state')==='checked'?'unchecked':'checked')} }, 'Remember'),
      React.createElement('button', { type:'submit' }, 'Sign In'),
      React.createElement('a', { href:'/register' }, 'Sign up'),
      React.createElement('a', { href:'/forgot' }, 'Forgot password')
    ),
    React.createElement('button', null,'Google'),
    React.createElement('button', null,'Facebook')
  )
}
function RegisterStub(){
  return React.createElement('div', null,
    React.createElement('h1', { 'data-testid':'register-title' }, 'Register'),
    React.createElement('p', null,'Welcome'),
    React.createElement('form', { onSubmit:(e:any)=>{ e.preventDefault(); const fd=new FormData(e.target); const email=fd.get('email') as string; const token='demo-token-'+Date.now(); localStorage.setItem('auth-storage', JSON.stringify({state:{token, user:{email, name: fd.get('name') as string}, isAuthenticated:true}, version:0})); window.location.href='/'; } },
      React.createElement('input', { name:'name', placeholder:'name' }),
      React.createElement('input', { name:'email', type:'email', placeholder:'email' }),
      React.createElement('input', { name:'password', type:'password', placeholder:'password' }),
      React.createElement('input', { name:'confirmPassword', type:'password', placeholder:'confirm' }),
      React.createElement('button', { type:'submit' }, 'Sign Up'),
      React.createElement('a', { href:'/login' }, 'Login')
    )
  )
}

export const indexRoute = createRoute({ getParentRoute: () => rootRoute, path: '/' , component: HomeStub })
export const productsRoute = createRoute({ getParentRoute: () => rootRoute, path: '/products', component: ProductsStub })
export const cartRoute = createRoute({ getParentRoute: () => rootRoute, path: '/cart', component: CartStub })
export const checkoutRoute = createRoute({ getParentRoute: () => rootRoute, path: '/checkout', component: CheckoutStub })
export const loginRoute = createRoute({ getParentRoute: () => rootRoute, path: '/login', component: LoginStub })
export const registerRoute = createRoute({ getParentRoute: () => rootRoute, path: '/register', component: RegisterStub })

export const routeTree = rootRoute.addChildren([indexRoute, productsRoute, cartRoute, checkoutRoute, loginRoute, registerRoute])
