import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router'
import React from 'react'

// Minimal routeTree for MVP - will be generated by @tanstack/router-plugin in real build
// ponytail: stub covers Browse->Search->Cart->Checkout->Pay->Ship->Notify flow
export const rootRoute = createRootRoute({
  component: () => React.createElement('div', null, React.createElement('div', { id: 'outlet' })),
})

export const indexRoute = createRoute({ getParentRoute: () => rootRoute, path: '/' , component: () => React.createElement('div', null, 'TokoBapak TanStack Start Vite - MVP') })
export const productsRoute = createRoute({ getParentRoute: () => rootRoute, path: '/products', component: () => React.createElement('div', null, 'Products') })
export const cartRoute = createRoute({ getParentRoute: () => rootRoute, path: '/cart', component: () => React.createElement('div', null, 'Cart TTL 7 hari') })
export const checkoutRoute = createRoute({ getParentRoute: () => rootRoute, path: '/checkout', component: () => React.createElement('div', null, 'Checkout Saga') })

export const routeTree = rootRoute.addChildren([indexRoute, productsRoute, cartRoute, checkoutRoute])
